# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:34
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "initial_data.json")



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    ]
