# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160526_1949'),
    ]

    operations = [
    ]
