# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160512_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password_two',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
